/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouBusinessRouteImport } from './routes/thank-you-business'
import { Route as IndicacaobusinessRouteImport } from './routes/indicacaobusiness'
import { Route as Contabil02RouteImport } from './routes/contabil02'
import { Route as ContabilThankYouRouteImport } from './routes/contabil-thank-you'
import { Route as ContabilRouteImport } from './routes/contabil'
import { Route as Businessv2RouteImport } from './routes/businessv2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Businessv2DiagnosticoRouteImport } from './routes/businessv2.diagnostico'

const ThankYouBusinessRoute = ThankYouBusinessRouteImport.update({
  id: '/thank-you-business',
  path: '/thank-you-business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacaobusinessRoute = IndicacaobusinessRouteImport.update({
  id: '/indicacaobusiness',
  path: '/indicacaobusiness',
  getParentRoute: () => rootRouteImport,
} as any)
const Contabil02Route = Contabil02RouteImport.update({
  id: '/contabil02',
  path: '/contabil02',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilThankYouRoute = ContabilThankYouRouteImport.update({
  id: '/contabil-thank-you',
  path: '/contabil-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilRoute = ContabilRouteImport.update({
  id: '/contabil',
  path: '/contabil',
  getParentRoute: () => rootRouteImport,
} as any)
const Businessv2Route = Businessv2RouteImport.update({
  id: '/businessv2',
  path: '/businessv2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Businessv2DiagnosticoRoute = Businessv2DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => Businessv2Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/businessv2': typeof Businessv2RouteWithChildren
  '/contabil': typeof ContabilRoute
  '/contabil-thank-you': typeof ContabilThankYouRoute
  '/contabil02': typeof Contabil02Route
  '/indicacaobusiness': typeof IndicacaobusinessRoute
  '/thank-you-business': typeof ThankYouBusinessRoute
  '/businessv2/diagnostico': typeof Businessv2DiagnosticoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/businessv2': typeof Businessv2RouteWithChildren
  '/contabil': typeof ContabilRoute
  '/contabil-thank-you': typeof ContabilThankYouRoute
  '/contabil02': typeof Contabil02Route
  '/indicacaobusiness': typeof IndicacaobusinessRoute
  '/thank-you-business': typeof ThankYouBusinessRoute
  '/businessv2/diagnostico': typeof Businessv2DiagnosticoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/businessv2': typeof Businessv2RouteWithChildren
  '/contabil': typeof ContabilRoute
  '/contabil-thank-you': typeof ContabilThankYouRoute
  '/contabil02': typeof Contabil02Route
  '/indicacaobusiness': typeof IndicacaobusinessRoute
  '/thank-you-business': typeof ThankYouBusinessRoute
  '/businessv2/diagnostico': typeof Businessv2DiagnosticoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/businessv2'
    | '/contabil'
    | '/contabil-thank-you'
    | '/contabil02'
    | '/indicacaobusiness'
    | '/thank-you-business'
    | '/businessv2/diagnostico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/businessv2'
    | '/contabil'
    | '/contabil-thank-you'
    | '/contabil02'
    | '/indicacaobusiness'
    | '/thank-you-business'
    | '/businessv2/diagnostico'
  id:
    | '__root__'
    | '/'
    | '/businessv2'
    | '/contabil'
    | '/contabil-thank-you'
    | '/contabil02'
    | '/indicacaobusiness'
    | '/thank-you-business'
    | '/businessv2/diagnostico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Businessv2Route: typeof Businessv2RouteWithChildren
  ContabilRoute: typeof ContabilRoute
  ContabilThankYouRoute: typeof ContabilThankYouRoute
  Contabil02Route: typeof Contabil02Route
  IndicacaobusinessRoute: typeof IndicacaobusinessRoute
  ThankYouBusinessRoute: typeof ThankYouBusinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you-business': {
      id: '/thank-you-business'
      path: '/thank-you-business'
      fullPath: '/thank-you-business'
      preLoaderRoute: typeof ThankYouBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacaobusiness': {
      id: '/indicacaobusiness'
      path: '/indicacaobusiness'
      fullPath: '/indicacaobusiness'
      preLoaderRoute: typeof IndicacaobusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabil02': {
      id: '/contabil02'
      path: '/contabil02'
      fullPath: '/contabil02'
      preLoaderRoute: typeof Contabil02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabil-thank-you': {
      id: '/contabil-thank-you'
      path: '/contabil-thank-you'
      fullPath: '/contabil-thank-you'
      preLoaderRoute: typeof ContabilThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabil': {
      id: '/contabil'
      path: '/contabil'
      fullPath: '/contabil'
      preLoaderRoute: typeof ContabilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businessv2': {
      id: '/businessv2'
      path: '/businessv2'
      fullPath: '/businessv2'
      preLoaderRoute: typeof Businessv2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businessv2/diagnostico': {
      id: '/businessv2/diagnostico'
      path: '/diagnostico'
      fullPath: '/businessv2/diagnostico'
      preLoaderRoute: typeof Businessv2DiagnosticoRouteImport
      parentRoute: typeof Businessv2Route
    }
  }
}

interface Businessv2RouteChildren {
  Businessv2DiagnosticoRoute: typeof Businessv2DiagnosticoRoute
}

const Businessv2RouteChildren: Businessv2RouteChildren = {
  Businessv2DiagnosticoRoute: Businessv2DiagnosticoRoute,
}

const Businessv2RouteWithChildren = Businessv2Route._addFileChildren(
  Businessv2RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Businessv2Route: Businessv2RouteWithChildren,
  ContabilRoute: ContabilRoute,
  ContabilThankYouRoute: ContabilThankYouRoute,
  Contabil02Route: Contabil02Route,
  IndicacaobusinessRoute: IndicacaobusinessRoute,
  ThankYouBusinessRoute: ThankYouBusinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
